{
 "title": "Pipeline Metrics (BMI)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up time (d HH:MM:SS)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "dtdhms",
   "valueName": "current",
   "targets": [
    { "expr": "server_up_time_total" }
   ]
  },
  {
   "title": "Classification Labels Seen",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_classification_outcome_total\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Classification Labels Seen (Series)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\".*_classification_outcome_total\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Requests Handled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests_handled_total", "legendFormat": "Requests Handled" }
   ]
  },
  {
   "title": "System Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "Total CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage * 100", "legendFormat": "Total CPU Usage" }
   ]
  },
  {
   "title": "Classification Labels Seen (Log base 2)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_classification_outcome_total\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Classification Labels Seen (Series)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*_classification_outcome_total\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes / 1024 / 1024",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}